---

driver                      :
    name                    : docker
    socket                  : unix:///var/run/docker.sock
    use_sudo                : false

driver_config               :
     image                  : ubuntu:14.04
     platform               : ubuntu

provisioner                 :
    name                    : ansible_push
    ansible_config          : "test/ansible.cfg"
    idempotency_test        : true

platforms:
    - name                  : "ubuntu_V1.9"
      provisioner           :
        ansible_playbook_bin: "`avm path v1.9`ansible-playbook"

    - name                  : "ubuntu_V2.0"
      provisioner           :
        ansible_playbook_bin: "`avm path v2.0`ansible-playbook"

    - name                  : "ubuntu_V2.1"
      provisioner           :
        ansible_playbook_bin: "`avm path v2.1`ansible-playbook"

    - name                  : "ubuntu_V2.2"
      provisioner           :
        ansible_playbook_bin: "`avm path v2.2`ansible-playbook"

    - name                  : "ubuntu_V2.3"
      provisioner           :
        ansible_playbook_bin: "`avm path v2.3`ansible-playbook"

suites                      :
  - name                    : simpleNoChef
    provisioner             :
      playbook              : "test/application/simple.yml"
      chef_bootstrap_url    : nil

  - name                    : simpleWithChef
    provisioner             :
      playbook              : "test/application/simple.yml"

  - name                    : notidempotent
    provisioner             :
      playbook              : "test/application/notidempotent.yml"
      fail_non_idempotent   : false
      chef_bootstrap_url    : nil
